//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OffbeatTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reward
    {
        public int Id { get; set; }
        public string ItemName { get; set; }
        public byte Quantity { get; set; }
        public byte Posetion { get; set; }
    }
}
